/**
* @name: dialog
* @author: DELL
* @date: 2022/10/26 17:12
* @description：dialog
* @update: 2022/10/26 17:12
*/
<!-- 页面 -->
<template>
  <div v-if="visible" class="slide-top box" :class="{ [type] : true}">
    <div class="title"><span>{{type === 'danger'? '设备故障预警' : '设备信息'}}</span></div>
    <div class="box2">
      <div class="box3">
        <div>启停机峰值</div>
        <div>35.395</div>
      </div>
      <div class="box4">
        <div>设备温度</div>
        <div> 47.4</div>
      </div>
      <div class="box5">
        <div>加速度包格峰值</div>
        <div class="red"> 75.098</div>
      </div>
      <div class="box6">
        <div>速度有效值</div>
        <div class="red">5998</div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    visible: {
      type: Boolean,
      default: false
    },
    type: {
      type: String,
      default: 'danger'
    }
  },
  data() {
    return {};
  },

  components: {},

  computed: {},

  mounted() {
  },

  methods: {},
  name: "dialog",
};
</script>

<style lang='scss' scoped>
.box {
  position: absolute;
  width: 424px;
  height: 267px;
  left: 586px;
  top: 222px;
  &.danger {
    .title {
      color: #F34336;
      background: url(~@/assets/images/dialogTitle.png) no-repeat center;
      background-size: 100% 100%;
    }
    .box2{
      border: 2px solid #F34336;
      background: rgba(43, 5, 5, 0.43);
    }
    .red {
      color: #F34336;
    }
  }
  &.success {
    .title {
      color: #fff;
      background: url(~@/assets/images/dialogB.png) no-repeat center;
      background-size: 100% 100%;
    }
    .box2{
      border: 2px solid #1D3FA1;
      background: rgba(27,45,126, 0.23);
    }
    .red {
      color: #FFFFFF;
    }
  }

  .title {
    width: 420px;
    height: 45px;
    margin-bottom: 10px;
    font-family: 'Microsoft YaHei';
    font-style: normal;
    font-weight: 400;
    font-size: 20px;
    line-height: 26px;

    /* danger */

    box-sizing: border-box;
    & > span {
      display: inline-block;
      padding-top: 5px;
      margin-left: 70px;
    }
  }

  .box2 {
    box-sizing: border-box;
    width: 420px;
    height: 200px;
    left: 590px;
    top: 289px;
    padding: 20px 18px;


    box-sizing: border-box;

    .box3, .box5 {
      width: 386px;
      height: 44px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 22px;
      font-size: 16px;
      color: #FFFFFF;
      background: rgba(30, 30, 47, 0.6);
      border-radius: 12px;
      box-sizing: border-box;
    }

    .box4, .box6 {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 22px;
      font-size: 16px;
      color: #FFFFFF;
      width: 386px;
      height: 44px;
      box-sizing: border-box;
    }

  }
}

.slide-top {
  -webkit-animation: slide-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: slide-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-26 17:15:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
  }
}

@keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
  }
}

</style>
