/**
* @name: left
* @author: DELL
* @date: 2022/10/24 16:04
* @description：left
* @update: 2022/10/24 16:04
*/
<!-- 页面 -->
<template>
  <div class="left slide-right">
    <div class="leftBox">

        <div class="box slide-top" v-show="v1">
          <div class="homeName" @click="goBack" ></div>
          <div class="bar">
            <div class="title">涂装车间 > 离心式风机061</div>
            <div class="contentBox">
              <div class="name">离心式风机 【BLBC61】</div>
              <div class="info">
                <div class="infoItem">Size: <span class="m-l-10">61.5</span></div>
                <div class="infoItem">
                  Product Type: <span class="m-l-10">BLBC</span>
                </div>
              </div>
              <div class="info">
                <div class="infoItem">Item Type: <span class="m-l-10">Fan Section</span></div>
              </div>
              <div class="info">
                <div class="infoItem">Handing: <span class="m-l-10">L35</span></div>
                <div class="infoItem">
                  Driving Arrgt: <span class="m-l-10">2A</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="bar2 slide-top" v-if="v2">
          <div class="title">涂装车间 > 离心式风机分布图</div>
          <div class="images">
          </div>
        </div>
    </div>
  </div>
</template>

<script>

export default {
  data() {
    return {
      v1: false,
      v2: false,
    };
  },

  components: {},

  computed: {},

  mounted() {
    setTimeout(() => {
      this.v1 = true;
    }, 500);
    this.$nextTick(() => {
      setTimeout(() => {
        this.v2 = true;
      }, 750);
    })
  },

  methods: {
    goBack() {
      this.$router.push('/');
    }
  },
  beforeDestroy() {
    window.removeEventListener('resize', () => {
    });
  },
  name: "left",
};
</script>

<style lang='scss' scoped>
.slide-right {
  -webkit-animation: slide-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: slide-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

.left {
  position: absolute;
  width: 463px;
  //height: 1024px;
  //left: 5px;
  top: 54px;
  left: -458px;
  bottom: 0;
  background: linear-gradient(91.81deg, rgba(23, 23, 23, 0.8) 44.64%, rgba(23, 23, 23, 0) 98.94%);

  .leftBox {
    width: 100%;
    height: 100%;
    position: relative;
    overflow: hidden;

    .homeName {
      width: 254px;
      height: 58px;
      background: url(~@/assets/images/return.png) no-repeat;
      background-size: 100% 100%;
      position: absolute;
      width: 244px;
      height: 40px;
      left: 51px;
      top: 253px;
      cursor: pointer;
    }

    .bar {
      position: absolute;
      width: 360px;
      height: 245px;
      left: 29px;
      top: 350px;
      background: rgba(38, 38, 38, 0.2);
      border: 1px solid #416CD9;
      box-sizing: border-box;

      .title {
        width: 340px;
        height: 30px;
        margin: 20px auto;
        font-size: 14px;
        padding-left: 25px;
        padding-top: 5px;
        color: #FFFFFF;
        background: url(~@/assets/images/itemTime.png) no-repeat;
        background-size: 100% 100%;
        box-sizing: border-box;
      }

      .contentBox {
        .name {
          margin: 0 23px 20px 23px;
          color: #FFFFFF;
        }

        .info {
          display: flex;
          width: 340px;
          margin: 0 auto;
          line-height: 34px;
          border-bottom: 1px solid #416CD9;
          box-sizing: border-box;

          .infoItem {
            flex: 1;
            font-size: 14px;
            color: #D4D4D4;
          }
        }
      }
    }

    .bar2 {
      position: absolute;
      width: 360px;
      height: 245px;
      left: 29px;
      top: 624px;
      border: 1px solid #416CD9;
      background: rgba(38, 38, 38, 0.2);
      box-sizing: border-box;

      .title {
        width: 340px;
        height: 30px;
        margin: 20px auto;
        font-size: 14px;
        padding-left: 25px;
        padding-top: 5px;
        color: #FFFFFF;
        background: url(~@/assets/images/itemTime.png) no-repeat;
        background-size: 100% 100%;
        box-sizing: border-box;
      }

      .images {
        width: 354px;
        height: calc(245px - 35px - 40px);
        margin: 0 auto;
        background: url(~@/assets/images/imags.png) no-repeat center;
        background-size: 100% 100%;
      }
    }

    .m-l-10 {
      margin-left: 10px;
    }
  }
}
.box{
  height: 342px;
  position: absolute;
  width: 244px;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-27 10:47:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-right {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  100% {
    -webkit-transform: translateX(100px);
    transform: translateX(463px);
  }
}

@keyframes slide-right {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  100% {
    -webkit-transform: translateX(463px);
    transform: translateX(463px);
  }
}

.slide-top {
  -webkit-animation: slide-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: slide-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-26 17:15:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
    opacity: 1;
  }
}

@keyframes slide-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
    opacity: 1;
  }
}
</style>
